### ISSUE TITLE
Update navbar style

### ISSUE THREAD

**Issue by doutatsu** [BridgeU/bridget#11]
We currently have not up to date styling for the navbar. Here are three different styles I found:

## Bridget Style
![localhost_3000_campaigns_new](https://user-images.githubusercontent.com/4270980/56889685-f4f2a400-6a6e-11e9-923e-c4b5809ecb82.png)

## BridgeU Connect (current design)
![bridgeu-universities herokuapp com_](https://user-images.githubusercontent.com/4270980/56889689-f91ec180-6a6e-11e9-964f-6a66051b48d8.png)

## Invision design (BridgeU Campaigns)
![image](https://user-images.githubusercontent.com/4270980/56889700-020f9300-6a6f-11e9-99be-9dec29744fa1.png)

As can be seen, the padding, font size active element and even width of the navbar are different. After chatting with @gnclmorais, I know we want to have a fixed width, but it's not a priority right now.

What is though, is having Connect and Campaigns navbar to be the same. If we are to add the same styling on Connect now, I'd rather we add it to Bridget instead, to reduce stylesheet duplication.

So I wanted to hear from @alexbridgeu or @shrihari, if we want to roll in some extra changes (font size, different padding) or if we should for now just use BridgeU Connect as the reference for the design

**Comment by gnclmorais** [comment]
Don’t forget that you can use the same classes in order to replicate the max-width effect on Campaigns:
![image](https://user-images.githubusercontent.com/385232/56890899-a8a96300-6a72-11e9-8f74-1c8cb108376c.png)

**Comment by gnclmorais** [comment]
@doutatsu, do you think this is now fixed?

**Comment by doutatsu** [comment]
This has been fixed for a while, with a completely new style of navbar
