### ISSUE TITLE
INFO: Vulnerability found: jquery below 3.4.0

### ISSUE THREAD

**Issue by fernandozartis** [BridgeU/bridget#8]
Hi Guys,
  We are using Bridget in campaigns project and we have executed[ dependency-check](https://www.owasp.org/index.php/OWASP_Dependency_Check) to verify the project and realize Bridget has a security risk dependency.

**_./dependency-check.sh --project Testing --out . --scan /source/bridget/ --enableExperimental_**

> RESULT: **INFO: Vulnerability found: jquery below 3.4.0**

"bridget@https://github.com/BridgeU/bridget.git":
  version "0.0.1"
  resolved "https://github.com/BridgeU/bridget.git#0b95d44097e06208d18f84a178610c10fa6790b9"
  dependencies:
    bootstrap "^4.3.1"
    jquery "^3.3.1"
    popper.js "^1.14.7"

**Comment by gnclmorais** [comment]
Thanks! For future reference, [`npm audit`](https://blog.npmjs.org/post/173719309445/npm-audit-identify-and-fix-insecure) performs a similar job:
```
➤ npm audit                                                                                                               16:47:36

                       === npm audit security report ===

# Run  npm install jquery@3.4.0  to resolve 1 vulnerability
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ jquery                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ jquery                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ jquery                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/796                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
```
